### PR TITLE
hide search operators behind autocompletion list

### PR DESCRIPTION
**Pull request by quintinali**
It's weird having search operators jump all over the place as the size of the suggestion list changes. Search operators are hidden behind autocompletion list in this PR.

### CODE REVIEW

**Comment by quintinali** [comment]
@fgreg  I just modified one file named 'controller.js'. It is weird that 14 files are changed in the PR. Does that matter?

**Comment by fgreg** [comment]
@quintinali It depends on where you branched from. I can't tell from here but it looks like you branched from some point behind master and then merged master into your new branch. You could just branch from mudrod/mudrod-117 and then you'd see only the one file changed.

Isn't this what it was before you changed it? Now the behavior is back where the options disappear entirely once you start typing. So if you type a letter, then press backspace the options are gone.

The options shouldn't move or hide. Just stay where they are and the drop down goes 'over' them.

**Comment by quintinali** [comment]
Could @gxtchen help solving this issue? I can't solve it since I am unfamiliar with AngularJS. Thanks.

**Comment by fgreg** [comment]
@quintinali I'll take a stab at it in another PR.

**Pull request closed without merging**
