### PR TITLE
Added a ssl log checker

### PR DESCRIPTION
**Pull request by Yongyao**
Added a snippet of code to find the log file that starts with "ssl_".

### CODE REVIEW

**Review by fgreg — CHANGES_REQUESTED** [review]
I think it would be better if this code simply checked if any files in `DATA_DIR` have filenames that contain `HTTP_PREFIX`. As it is, this code will break if the filename changes again.

We're using Java 8 so we can use the standard library to find files that match a pattern:

https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPathMatcher-java.lang.String-

http://docs.oracle.com/javase/tutorial/essential/io/find.html

**Comment by lewismc** [comment]
ack I agree @fgreg 
Additionally @Yongyao can you please name your variables using Java code cenvention e.g. ```httplogpathWww``` rather than ```httplogpath_www```. The latter compiles and runs less efficiently.

**Comment by Yongyao** [comment]
@fgreg Could you please check again? I didn't use the getpathmacher() you suggested as I still need to loop the directory no matter what, but I think this is fine.

**Comment by fgreg** [comment]
That looks better. I'll try testing before our meeting tomorrow

**Comment by lewismc** [comment]
@Yongyao we need to find if Chris Finch is going to continue to provide both WWW and WWWssl logs or if he is only going to provide WWWssl...
The reason I am mentioning this is that the default [httpPrefix](https://github.com/mudrod/mudrod/blob/master/core/src/main/resources/config.xml#L48) property value should possibly change within config.xml. I do see however that the code you've provided looks for ```if (file.getName().contains``` meaning that this really shouldn't matter too much.

I tried ingesting the most recent week worth of logs and I am getting an issue. I'll debug further tomorrow.

**Review by fgreg — APPROVED** [review]

**Pull request merged**
