### PR TITLE
Mudrod 68

### PR DESCRIPTION
**Pull request by quintinali**
1. clean esdriver.java
2. solve problem of loading svm model on windows system

### CODE REVIEW

**Review by lewismc — COMMENTED** [review]
Hi @quintinali can you please format your code as per the existing MUDROD formatting?

**Review by lewismc — CHANGES_REQUESTED** [review]
Additionally, we need to make sure that the system definitely deploys on a *nix distribution. Windows is of secondary importance and I am not sure if we are even interested in supporting Windows right now t be honest as no production machines we maintain run Windows.

**Comment by quintinali** [comment]
@lewismc I'm sorry that I have deleted .metadata directory in the eclipse workspace and didn't notice the format changed back to the default format. I will format the codes and resubmit them.

I modified the code to support windows system because I develop MUDROD in my laptop which uses windows system. MUDROD web service can't start without modification and then I can't test web related functions. Please see details in https://github.com/mudrod/mudrod/issues/135

**Comment by lewismc** [comment]
@quintinali I understand that you are developing code on your Windows laptop... however MUDROD is being transitioned to PO.DAAC... which uses Redhat servers... not Windows. Please keep in mind what the issue is meant to address. The issue as described over on #68 is **ESDriver cleanup**... not **ESDriver cleanup, edit build systems such that deployment works on Windows, etc.**
Let's try and keep things simple, clean and easier for everyone. Otherwise the [development workflow](https://github.com/mudrod/mudrod/wiki/Mudrod-Development-Workflow) cracks and crumbles and we are left with a low standard of code which is difficult to maintain.
If getting MUDROD running on Windows is still such an issue for you then there are two options...
 * use *nix environment, I'm sure that some people at George Mason University are pretty familiarized with this already e.g. @Yongyao and it would take probably around 10 minutes to get you set up with this, or
 * the entire MUDRDO development team have a technical session and we fix this once and for all. 

This has lingered on way too long, especially for something which is not going to be supported at PO.DAAC.

**Comment by quintinali** [comment]
@lewismc I'm sorry that this pull request provides more functions than the title describes which makes it confusion. I didn't intentionally to do that. After I finished ESDriver cleanup, I merged the master into my branch and found the web service can't start due to conflict with other commits. I have to revise my code to support Windows in order to further test my modification in the new version (I didn't know we can just support *nix at that time). That's why my pull request did much more than expected.

Thanks for your suggestions. I think a better choice is:
(1) close this pull request.
(2) submit the code into two pull requests, one is fixing windows issue https://github.com/mudrod/mudrod/issues/135  because frank and I have fixed it, another one is cleaning esdriver https://github.com/mudrod/mudrod/issues/68.

How do you think about it? thanks.

**Comment by lewismc** [comment]
@quintinali yes please this sounds much cleaner. Thank you

**Pull request closed without merging**
