### PR TITLE
Cc es hadoop

### PR DESCRIPTION
**Pull request by quintinali**
Please don't merge it to master since modifications in this function are not finished yet.

Main modifications in this branch:

Update Elasticsearch from 2.3 to 5.0-beta1
Add Elasticsearch-spark library
Parallelize log import, crawler detection, session reconstruction. The original sequential functions are kept for comparison.
Elasticsearch API changes due to upgrading of elasticsearch

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @quintinali I looked into this earlier in the week and also got distracted for a while but now I am back debugging and have made some good progress.
I'm at the following stage

```
lmcgibbn@LMC-056430 /usr/local/mudrod/core(cc_es_hadoop) $ spark_submit --class esiptestbed.mudrod.main.MudrodEngine ./target/mudrod-core-uber-0.0.1-SNAPSHOT.jar -f -logDir /usr/local/mudrod_resources/Testing_Data_2_ProcessedLog+Meta+Onto/
...
java.lang.IllegalArgumentException: [size] must be greater than 0. Found [0] in [IPs]
    at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregationBuilder.size(TermsAggregationBuilder.java:117)
    at esiptestbed.mudrod.weblog.pre.HistoryGenerator.GenerateBinaryMatrix(HistoryGenerator.java:97)
    at esiptestbed.mudrod.weblog.pre.HistoryGenerator.execute(HistoryGenerator.java:59)
    at esiptestbed.mudrod.discoveryengine.WeblogDiscoveryEngine.preprocess(WeblogDiscoveryEngine.java:159)
    at esiptestbed.mudrod.main.MudrodEngine.startFullIngest(MudrodEngine.java:162)
    at esiptestbed.mudrod.main.MudrodEngine.main(MudrodEngine.java:394)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

I'm going to send a pull request before I got home for the day.

**Comment by lewismc** [comment]
@Yongyao @quintinali what does the following property relate to?
https://github.com/mudrod/mudrod/blob/master/core/src/main/java/esiptestbed/mudrod/weblog/pre/HistoryGenerator.java#L68
It is not present in either out MudrodConstants on in config.xml...

**Comment by quintinali** [comment]
Hi, lewis, the issue "java.lang.IllegalArgumentException: [size] must be greater than 0. Found [0] in [IPs]" is caused by Elasticsearch API changes. I only changed codes related to command -l and -s  so far. 

I spent a lot of time solving problems I encountered when MUDROD is executed on a hdfs+spark+elasticsearch cluster and most parts work now except the hdfs cluster.  I will modify codes related to command '-f' after I solving this problem.

**Comment by quintinali** [comment]
@lewismc  userHistoryMatrix is defined here.
https://github.com/mudrod/mudrod/blob/master/core/src/main/java/esiptestbed/mudrod/main/MudrodEngine.java#L381

This property is related to a CSV file of user query behaviours generated from web logs.

**Comment by lewismc** [comment]
@quintinali because you merged the code over on https://github.com/quintinali/mudrod/pull/1 it has already been updated here. Thank you. Please lets have a call later on today to discuss what is going on with the development as we need to synchronize here.

**Comment by lewismc** [comment]
I'm working on it. I will let you know when I finish it

**Comment by quintinali** [comment]
@lewismc I think cc_es_hadoop branch is ready to merge to master branch. I tested most functionalities and they work well except autocomplete function in the mudrodengine.java and Mudrod :: Service.  Maybe we could fix them later?

[INFO] Mudrod :: Parent ................................... SUCCESS [ 16.195 s]
[INFO] Mudrod :: Core ..................................... SUCCESS [01:37 min]
[INFO] Mudrod :: Service .................................. FAILURE [  2.688 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:56 min
[INFO] Finished at: 2017-02-01T14:45:08-08:00
[INFO] Final Memory: 84M/644M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project mudrod-service: Compilation failure: Compilation failure:
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/search/SearchMetadataResource.java:[18,21] package javax.servlet does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/search/SearchMetadataResource.java:[51,42] cannot find symbol
[ERROR] symbol:   class ServletContext
[ERROR] location: class esiptestbed.mudrod.services.search.SearchMetadataResource
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/MudrodContextListener.java:[18,21] package javax.servlet does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/MudrodContextListener.java:[19,21] package javax.servlet does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/MudrodContextListener.java:[20,21] package javax.servlet does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/MudrodContextListener.java:[21,32] package javax.servlet.annotation does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/MudrodContextListener.java:[34,47] cannot find symbol
[ERROR] symbol: class ServletContextListener
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/MudrodContextListener.java:[33,2] cannot find symbol
[ERROR] symbol: class WebListener
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/MudrodContextListener.java:[48,32] cannot find symbol
[ERROR] symbol:   class ServletContextEvent
[ERROR] location: class esiptestbed.mudrod.services.MudrodContextListener
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/MudrodContextListener.java:[56,34] cannot find symbol
[ERROR] symbol:   class ServletContextEvent
[ERROR] location: class esiptestbed.mudrod.services.MudrodContextListener
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/autocomplete/AutoCompleteResource.java:[19,21] package javax.servlet does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/autocomplete/AutoCompleteResource.java:[47,40] cannot find symbol
[ERROR] symbol:   class ServletContext
[ERROR] location: class esiptestbed.mudrod.services.autocomplete.AutoCompleteResource
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/recommendation/RecomDatasetsResource.java:[16,21] package javax.servlet does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/recommendation/RecomDatasetsResource.java:[30,51] cannot find symbol
[ERROR] symbol:   class RecommendationData
[ERROR] location: package esiptestbed.mudrod.recommendation.structure
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/recommendation/RecomDatasetsResource.java:[40,41] cannot find symbol
[ERROR] symbol:   class ServletContext
[ERROR] location: class esiptestbed.mudrod.services.recommendation.RecomDatasetsResource
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/search/SessionDetailResource.java:[16,21] package javax.servlet does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/search/SessionDetailResource.java:[47,41] cannot find symbol
[ERROR] symbol:   class ServletContext
[ERROR] location: class esiptestbed.mudrod.services.search.SessionDetailResource
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/search/SearchDatasetDetailResource.java:[20,21] package javax.servlet does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/search/SearchDatasetDetailResource.java:[48,47] cannot find symbol
[ERROR] symbol:   class ServletContext
[ERROR] location: class esiptestbed.mudrod.services.search.SearchDatasetDetailResource
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/search/SearchVocabResource.java:[17,21] package javax.servlet does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/search/SearchVocabResource.java:[18,21] package javax.servlet does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/search/SearchVocabResource.java:[19,26] package javax.servlet.http does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/search/SearchVocabResource.java:[51,39] cannot find symbol
[ERROR] symbol:   class ServletContext
[ERROR] location: class esiptestbed.mudrod.services.search.SearchVocabResource
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/search/SearchVocabResource.java:[68,14] cannot find symbol
[ERROR] symbol:   class ServletException
[ERROR] location: class esiptestbed.mudrod.services.search.SearchVocabResource
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/recommendation/HybridRecomDatasetsResource.java:[16,21] package javax.servlet does not exist
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/recommendation/HybridRecomDatasetsResource.java:[40,47] cannot find symbol
[ERROR] symbol:   class ServletContext
[ERROR] location: class esiptestbed.mudrod.services.recommendation.HybridRecomDatasetsResource
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/MudrodContextListener.java:[47,3] method does not override or implement a method from a supertype
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/MudrodContextListener.java:[55,3] method does not override or implement a method from a supertype
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/MudrodContextListener.java:[62,5] cannot find symbol
[ERROR] symbol:   class ServletContext
[ERROR] location: class esiptestbed.mudrod.services.MudrodContextListener
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/recommendation/RecomDatasetsResource.java:[59,7] cannot find symbol
[ERROR] symbol:   class RecommendationData
[ERROR] location: class esiptestbed.mudrod.services.recommendation.RecomDatasetsResource
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/recommendation/RecomDatasetsResource.java:[59,38] cannot find symbol
[ERROR] symbol:   class RecommendationData
[ERROR] location: class esiptestbed.mudrod.services.recommendation.RecomDatasetsResource
[ERROR] /D:/Java workspace/mudrod/service/src/main/java/esiptestbed/mudrod/services/search/SessionDetailResource.java:[69,21] method getSessionDetail in class esiptestbed.mudrod.weblog.structure.Session cannot be applied to given types;
[ERROR] required: java.lang.String,java.lang.String,java.lang.String
[ERROR] found: java.lang.String,java.lang.String
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mudrod-service

**Comment by lewismc** [comment]
Great @quintinali I just fixed the above issues and submitted a pull request to your branch, pleasse merge https://github.com/quintinali/mudrod/pull/4

**Comment by quintinali** [comment]
@lewismc I merged your modification, then what should I do?

**Comment by lewismc** [comment]
@quintinali I am testing the branch right now. give me mayve 10 or so minutes so I can provide feedback. Thanks

**Comment by lewismc** [comment]
OK, I've verified core functionality is working with the new data provided by @Yongyao over at #85 . I am running Elasticsearch 5.X and Spark 2.X. All is running well.

@quintinali can you please merge into master? Thank you

**Comment by lewismc** [comment]
I'll go ahead and rebase #83

**Comment by quintinali** [comment]
@lewismc I just merged cc_es_haoop into master branch.

**Comment by lewismc** [comment]
Great thank you for all your work on this branch @quintinali :+1: 
I knew we would get there eventually :)

**Pull request merged**
