### PR TITLE
Spark2.0.0

### PR DESCRIPTION
**Pull request by lewismc**
This PR builds off of the temp0907 branch by upgrading spark to 2.0.0 as well as addressing a number of other issues such as #55, formatting issues, Javadoc and general code quality.

@Yongyao @quintinali I propose that we make an effort to test this branch ASAP and integrate it into master ASAP. We can then rebase on where we go next.

### CODE REVIEW

**Comment by lewismc** [comment]
@Yongyao can you please expand upon 'it doesn't work'?

If you mean it doesn't compile on your machine, then you need to pull the most recent code from the spark2.0.0 branch. If you look above at Travis-CI, you will see that it compiles absolutely fine and there are no merge issues. I am able to run full log ingestion.

@quintinali can you also please try to pull in the source code and compile and install?

**Comment by Yongyao** [comment]
Sure, it works on my office machine, but fails on my laptop. So I guess it is something about my local settings. However, I tried everything, including git clean, reset, checkout, remove .m2 folder and even remove the entire folder and download it again. Is it possibly related to maven version?

Just to clarify, I am not saying this branch is not working, instead I think it is ready to be merged into master, if we forget web service and reading rankingmodel from resource folder problem for now.

**Comment by lewismc** [comment]
Do you have local modifications on the spark2.0.0 branch?

**Comment by Yongyao** [comment]
Not at all.

**Comment by lewismc** [comment]
... I have no clue what it is then @Yongyao seriously. Which Java version are you using?

**Comment by Yongyao** [comment]
image

**Comment by lewismc** [comment]
Is it possible for you to log in to your Work machine and work from there?

**Comment by Yongyao** [comment]
Yeah, looks like that's the easiest way to go. Maybe I can try again after you merge it into master.

**Pull request merged**
