### PR TITLE
Fix for Mudrod 119

### LINKED ISSUE #119: Change how javaSVMWithSGDModel is loaded
Should not have to modify config.xml to include an absolute file path to the `javaSVMWithSGDModel` directory.

At the very lest this directory should be able to be loaded as a classpath resource.

### PR DESCRIPTION
**Pull request by fgreg**
This pull request fixes https://github.com/mudrod/mudrod/issues/119. It also includes some code format updates (increased line width from 80 to 200).

The way this works now is:

1. During the maven `generate-resources` phase, the assembly plugin execution with id `zipSVMWithSGDModel` is executed.
2. The `zipSVMWithSGDModel` execution uses `mudrod/core/src/main/assembly/zipSVMWithSGDModel.xml` to create a tar.gz archive of `mudrod/core/src/main/resources/javaSVMWithSGDModel`. The created archive called `javaSVMWithSGDModel.tar.gz` is placed into the `target` directory
3. The maven resources plugin excludes the `mudrod/core/src/main/resources/javaSVMWithSGDModel` directory and includes the `javaSVMWithSGDModel.tar.gz` archive so that the archive is placed in the root of the generated JAR file
4. When the application is started `gov.nasa.jpl.mudrod.main.MudrodEngine#loadConfig` calls the new method `gov.nasa.jpl.mudrod.main.MudrodEngine#decompressSVMWithSGDModel`. This method loads the archive from the classpath, decompresses it into a temporary directory, and returns the absolute file path to the new temporary directory
5. The absolute file path to the temporary directory is then passed on to the loader as before.

### CODE REVIEW

**Comment by lewismc** [comment]
@fgreg is the main change here related only to the new build additions? The remainder is just code formatting? Tanks @fgreg

**Comment by fgreg** [comment]
@lewismc Yes, the commit https://github.com/mudrod/mudrod/pull/124/commits/634333de3a0dc87dde2cfaad55696446fd05b0e2 contains the change to how javaSVMWithSGDModel is loaded.

The rest is just code formatting. I should have split the two but I committed to my branch without thinking and I didn't want to mess with git to fix it.

**Comment by lewismc** [comment]
Thats cool. I just wanted to make sure.

**Review by lewismc — APPROVED** [review]
+1 to merge into master. I also checked the new property value in core/src/main/resources/config.xml  and the value looks good.

**Pull request merged**
