### PR TITLE
MUDROD-148 Change order of elements on dataset details page

### PR DESCRIPTION
**Pull request by Yongyao**
Adjusted the order of dataset details as requested.

Merged attributes like “topic”, “variable” into a single “measurement” variable.

### CODE REVIEW

**Comment by lewismc** [comment]
```
[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 46.394 s

[INFO] Finished at: 2017-05-02T19:36:38+00:00

[INFO] Final Memory: 28M/219M

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal on project mudrod-core: Could not resolve dependencies for project gov.nasa.jpl.mudrod:mudrod-core:jar:0.0.1-SNAPSHOT: Could not transfer artifact org.apache.spark:spark-streaming_2.11:jar:2.1.0 from/to central (http://repo.maven.apache.org/maven2): GET request of: org/apache/spark/spark-streaming_2.11/2.1.0/spark-streaming_2.11-2.1.0.jar from central failed: Connection reset -> [Help 1]

[ERROR] 

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by lewismc** [comment]
@Yongyao the issue seems to be with the spark streaming dependency. Did this get added mor recently or has it been part of dependencies for a while?

**Review by lewismc — CHANGES_REQUESTED** [review]
Please see my comments @Yongyao

**Comment by Yongyao** [comment]
@lewismc Spark streaming is never used in this branch. I check all of the pom.xml files. None of them contain this dependency. Can you help take a look?

Also, only two files were changed in this PR, which has nothing to do with streaming

**Comment by lewismc** [comment]
ACK @Yongyao I thought so.... mmm. OK, I'll have a look. I am working on my deliverable for tomorrow I will look at this PR in due course. Thanks.

**Comment by Yongyao** [comment]
@lewismc Did you get a chance to look at this yet?

**Review by fgreg — APPROVED** [review]

**Pull request merged**
